server:
  port: 9443
  ssl:
    bundle: pizzeria-security-ssl
    client-auth: want

spring:

  application:
    name: "pizzeria-security-server"

  ssl:
    bundle:
      jks:
        pizzeria-security-ssl:
          key:
            alias: pizzeria-security-server
            password: password
          keystore:
            location: /home/claudio/IdeaProjects/pizzeria-fabulosa/security/pizzeria-security-server/src/main/resources/keystore.p12
            password: password
            type: PKCS12
          truststore:
            location: /home/claudio/IdeaProjects/pizzeria-fabulosa/security/pizzeria-security-server/src/main/resources/keystore.p12
            password: password
            type: PKCS12

  datasource:
    url: jdbc:mariadb://localhost:3306/pizzeria
    username: root
    password: root
    #    url: jdbc:mariadb://db:3306/pizzeria
    #    username: chef
    #    password: pizza
    hikari:
      initialization-fail-timeout: 60000

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
      jakarta:
        persistence:
          sharedCache:
            mode: UNSPECIFIED
    open-in-view: false
    hibernate:
      ddl-auto: update

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
