server:
  port: 8082

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    org.hibernate: INFO
    org.hibernate.sql: INFO

spring:

  application:
    name: "pizzeria-user-resource-server"

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9000/oauth2/jwks

  datasource:
    url: jdbc:mariadb://localhost:3306/pizzeria
    username: root
    password: root
    #    url: jdbc:mariadb://db:3306/pizzeria
    #    username: chef
    #    password: pizza
    hikari:
      initialization-fail-timeout: 60000

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true

      jakarta:
        persistence:
          sharedCache:
            mode: UNSPECIFIED

    open-in-view: false
    hibernate:
      ddl-auto: update

springdoc:
  api-docs:
    path: /api/v1/docs
  swagger-ui:
    path: /api/v1/docs/swagger
    operations-sorter: method
