server:
  port: 8082

spring:
  application:
    name: "pizzeria-assets-client"

springdoc:
  api-docs:
    path: /api/v1/docs
  swagger-ui:
    path: /api/v1/docs/swagger
    operations-sorter: method

logging:
  level:
    root: info
    org.springframework.security: info
    org.springframework.web: info