server:
  port: 8081

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.hibernate: INFO
    org.hibernate.sql: INFO

spring:
  application:
    name: "pizzeria-public-resource-server"
  datasource:
    url: jdbc:mariadb://localhost:3306/pizzeria
    username: root
    password: root
    #    url: jdbc:mariadb://db:3306/pizzeria
    #    username: chef
    #    password: pizza
    hikari:
      initialization-fail-timeout: 60000

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true

      jakarta:
        persistence:
          sharedCache:
            mode: UNSPECIFIED

    open-in-view: false
    hibernate:
      ddl-auto: update

springdoc:
  api-docs:
    path: /api/v1/docs
  swagger-ui:
    path: /api/v1/docs/swagger
    operations-sorter: method