server:
  port: 9000

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG

spring:

  application:
    name: "pizzeria-security-server"

  datasource:
    url: jdbc:mariadb://localhost:3306/pizzeria
    username: root
    password: root
    #    url: jdbc:mariadb://db:3306/pizzeria
    #    username: chef
    #    password: pizza
    hikari:
      initialization-fail-timeout: 60000

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
      jakarta:
        persistence:
          sharedCache:
            mode: UNSPECIFIED
    open-in-view: false
    hibernate:
      ddl-auto: update

angular-app:
  base-uri: http://127.0.0.1:4200
