server:
  port: 8080

spring:

  application:
    name: "pizzeria-user-client"

  security:
    oauth2:
      client:
        registration:
          user-client:
            provider: spring
            client-id: user-client
            client-name: user-client
            client-secret: user
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:8080/login/oauth2/code/{registrationId}"
            scope: openid, profile, email, phone, address
        provider:
          spring:
            issuer-uri: http://localhost:9000

  ssl:
    bundle:
      jks:
        user-client-ssl:
          key:
            alias: pizzeria-user-client
            password: password
          keystore:
            location: /home/claudio/IdeaProjects/pizzeria-fabulosa/api-client/pizzeria-user-client/src/main/resources/keystore.p12
            password: password
            type: PKCS12
          truststore:
            location: /home/claudio/IdeaProjects/pizzeria-fabulosa/api-client/pizzeria-user-client/src/main/resources/keystore.p12
            password: password
            type: PKCS12

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
